ALTER TABLE subscriptApp.article CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
SELECT SCHEMA_NAME
     , DEFAULT_CHARACTER_SET_NAME
     , DEFAULT_COLLATION_NAME
  FROM INFORMATION_SCHEMA.SCHEMATA
 ORDER BY SCHEMA_NAME;
 
ALTER DATABASE subscriptApp CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;